Create merging_strategy.md
antoine-cha/tips pull request #6
Opened 2017-08-07 14:03 UTC by antoine-wdg-rmz

2017-08-07 14:20 UTC, acg32 requested changes

2017-08-07 14:20 UTC, antoine-cha commented on _posts/merging_strategy.md
> +## Merging strategy
On n'a pas besoin de répéter le titre, il est déjà affiché grâce au template : https://antoine-cha.github.io/tips/2017/07/25/Git-list-files/

2017-08-07 14:20 UTC, antoine-cha commented on _posts/merging_strategy.md
> +Then open a PR on Bitbucket, and merge and **force a merge commit** (when merging manually,
La phrase peut sans doute être remplacée par une liste de points ? (2 "and" s'enchaînent).

2017-08-07 14:22 UTC, antoine-cha commented
N'oublie pas de renommer le fichier pour suivre la convention : https://github.com/antoine-cha/tips/tree/master/_posts

2017-08-08 07:54 UTC, antoine-wdg-rmz commented
Done

2017-08-08 08:14 UTC, merged