Create 2017-08-21-realworld-apps.md
antoine-cha/tips pull request #8
Opened 2017-08-21 10:22 UTC by antoine-wdg-rmz

2017-08-21 10:40 UTC, acg32 requested changes
Essaie de décrire un minimum ce que propose le site pour qu'on comprenne l'idée générale avant d'aller sur le site

2017-09-18 10:10 UTC, antoine-cha commented
ping

2017-09-18 12:16 UTC, antoine-wdg-rmz commented
pong

2017-09-18 14:07 UTC, antoine-cha commented
ping

2017-09-19 07:30 UTC, antoine-wdg-rmz commented
Done

2017-09-29 12:26 UTC, merged